version: '3'
services:
  column-forge-api:
    image: hakenadu/column-forge-api
    container_name: column-forge-api
    build:
      context: ./column-forge-api
    ports:
    - 8080:8080
  column-forge-ui:
    image: hakenadu/column-forge-ui
    container_name: column-forge-ui
    build:
      context: ./column-forge-ui
    environment:
      API_URL: http://localhost:8080
    ports:
    - 80:80